include color.conf
include maps.conf

#include gruvbox_dark_hard.conf
window_padding_width 18
background_opacity  .92

font_size 18
#copy_on_select clipboard
shell_integration no-cursor
cursor_blink_interval 0
cursor_shape underline
#disable_ligatures always
enable_audio_bell no
# initial_window_width  1200
# initial_window_height 800
remember_window_size  no
allow_remote_control true

tab_bar_edge top
tab_bar_style powerline
tab_powerline_style angled

# BEGIN_KITTY_FONTS
font_family      family='JetBrainsMono Nerd Font' postscript_name=JetBrainsMonoNF-Regular
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
