# preload = /home/kn/dev/photos/content/Rouen/10.jpg
# wallpaper = , /home/kn/dev/photos/content/Rouen/10.jpg

preload = /home/kn/Pictures/anime-moon-landscape-nord.jpg
wallpaper = , /home/kn/Pictures/anime-moon-landscape-nord.jpg
# preload = /home/kn/Pictures/wallhaven-zpxzrj.png
# wallpaper = , /home/kn/Pictures/wallhaven-zpxzrj.png

splash = false
ipc = off
