# preload = /home/kn/dev/photos/content/Rouen/10.jpg
# wallpaper = , /home/kn/dev/photos/content/Rouen/10.jpg

preload = /home/kn/Pictures/budapest/IMG_3251.JPG
wallpaper = , /home/kn/Pictures/budapest/IMG_3251.JPG

splash = false
ipc = off
