# JavaCafe01 Prompt

format = "$all"
add_newline = true

[hostname]
ssh_only = true
format = "[$hostname](bold blue) "
disabled = false

[directory]
truncation_length = 100
truncate_to_repo = false

[line_break]
disabled = false

[battery]
disabled = true
