#!/usr/bin/env bash

_step_size=${_step_size:-5}
_use_sudo=${_use_sudo:-0}

# whether to use `sudo` for changing the brightness (requires a NOPASSWD rule)
if [[ "$_use_sudo" == "0" ]] ; then
    LIGHT_SET="light"
else
    LIGHT_SET="sudo light"
fi

case $BLOCK_BUTTON in
  3) xset dpms force off ;; # right click
  4) $LIGHT_SET -A "$_step_size" ;; # scroll up
  5) $LIGHT_SET -U "$_step_size" ;; # scroll down, decrease
esac


BRIGHTNESS=$(light -G)
INT_BRIGHTNESS=${BRIGHTNESS%.*}
echo $INT_BRIGHTNESS ""
